package dev.gohst136.planetary.mod.world;

import dev.gohst136.planetary.world.ModificationDatabase;
import net.minecraft.core.BlockPos;
import net.minecraft.server.level.ServerLevel;
import net.minecraft.tags.BlockTags;
import net.minecraft.world.level.block.Block;
import net.minecraft.world.level.block.state.BlockState;
import net.neoforged.bus.api.SubscribeEvent;
import net.neoforged.fml.common.EventBusSubscriber;
import net.neoforged.neoforge.event.level.BlockEvent;

/**
 * Server side: records player edits in the planet's {@link ModificationDatabase} (singleplayer: the same JVM, so the client's far
 * field reads it directly; multiplayer: sent as ColumnTops, see docs/NETWORKING.md). Only levels generated by the planet generator.
 */
@EventBusSubscriber(modid = "planetary")
public final class PlanetEdits {
    private PlanetEdits() {}

    /** The world's edits (one planet per world for now). Not persisted yet: lost on restart (see docs). */
    public static final ModificationDatabase DB = new ModificationDatabase();

    @SubscribeEvent
    public static void broken(BlockEvent.BreakEvent e) {
        if (e.getLevel() instanceof ServerLevel level && isPlanet(level)) record(level, e.getPos());
    }

    @SubscribeEvent
    public static void placed(BlockEvent.EntityPlaceEvent e) {
        if (e.getLevel() instanceof ServerLevel level && isPlanet(level)) record(level, e.getPos());
    }

    private static boolean isPlanet(ServerLevel level) {
        return level.getChunkSource().getGenerator() instanceof PlanetChunkGenerator;
    }

    private static void record(ServerLevel level, BlockPos pos) {
        final int x = pos.getX(), y = pos.getY(), z = pos.getZ();
        // run after the change has been applied
        level.getServer().execute(() -> {
            BlockState now = level.getBlockState(new BlockPos(x, y, z));
            DB.setBlock(x, y, z, (short) (Block.getId(now) & 0xffff));
            DB.setColumnTop(x, z, groundTop(level, x, z));
        });
    }

    /** Topmost ground block (leaves, logs, plants and air do not count). */
    static int groundTop(ServerLevel level, int x, int z) {
        BlockPos.MutableBlockPos p = new BlockPos.MutableBlockPos();
        for (int y = level.getMaxBuildHeight() - 1; y >= level.getMinBuildHeight(); y--) {
            BlockState st = level.getBlockState(p.set(x, y, z));
            if (!st.isAir() && !st.is(BlockTags.LEAVES) && !st.is(BlockTags.LOGS) && st.blocksMotion()) return y;
        }
        return level.getMinBuildHeight();
    }
}
